(function() {var implementors = {};
implementors["rocket_app"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"rocket_app/domain/error/err_msg/_core/prelude/v1/trait.Default.html\" title=\"trait rocket_app::domain::error::err_msg::_core::prelude::v1::Default\">Default</a> for <a class=\"struct\" href=\"rocket_app/domain/version/struct.Version.html\" title=\"struct rocket_app::domain::version::Version\">Version</a>&lt;T&gt;",synthetic:false,types:["rocket_app::domain::version::Version"]},{text:"impl <a class=\"trait\" href=\"rocket_app/domain/error/err_msg/_core/prelude/v1/trait.Default.html\" title=\"trait rocket_app::domain::error::err_msg::_core::prelude::v1::Default\">Default</a> for <a class=\"struct\" href=\"rocket_app/domain/customers/resolver/struct.CustomersResolver.html\" title=\"struct rocket_app::domain::customers::resolver::CustomersResolver\">CustomersResolver</a>",synthetic:false,types:["rocket_app::domain::customers::resolver::CustomersResolver"]},{text:"impl <a class=\"trait\" href=\"rocket_app/domain/error/err_msg/_core/prelude/v1/trait.Default.html\" title=\"trait rocket_app::domain::error::err_msg::_core::prelude::v1::Default\">Default</a> for <a class=\"struct\" href=\"rocket_app/domain/orders/resolver/struct.OrdersResolver.html\" title=\"struct rocket_app::domain::orders::resolver::OrdersResolver\">OrdersResolver</a>",synthetic:false,types:["rocket_app::domain::orders::resolver::OrdersResolver"]},{text:"impl <a class=\"trait\" href=\"rocket_app/domain/error/err_msg/_core/prelude/v1/trait.Default.html\" title=\"trait rocket_app::domain::error::err_msg::_core::prelude::v1::Default\">Default</a> for <a class=\"struct\" href=\"rocket_app/domain/products/resolver/struct.ProductsResolver.html\" title=\"struct rocket_app::domain::products::resolver::ProductsResolver\">ProductsResolver</a>",synthetic:false,types:["rocket_app::domain::products::resolver::ProductsResolver"]},{text:"impl <a class=\"trait\" href=\"rocket_app/domain/error/err_msg/_core/prelude/v1/trait.Default.html\" title=\"trait rocket_app::domain::error::err_msg::_core::prelude::v1::Default\">Default</a> for <a class=\"struct\" href=\"rocket_app/domain/struct.Resolver.html\" title=\"struct rocket_app::domain::Resolver\">Resolver</a>",synthetic:false,types:["rocket_app::domain::resolver::Resolver"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
